/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/productos': typeof ProductosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/productos': typeof ProductosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/faq': typeof FaqRoute
  '/galeria': typeof GaleriaRoute
  '/nosotros': typeof NosotrosRoute
  '/productos': typeof ProductosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/contacto' | '/faq' | '/galeria' | '/nosotros' | '/productos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/faq' | '/galeria' | '/nosotros' | '/productos'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/faq'
    | '/galeria'
    | '/nosotros'
    | '/productos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  FaqRoute: typeof FaqRoute
  GaleriaRoute: typeof GaleriaRoute
  NosotrosRoute: typeof NosotrosRoute
  ProductosRoute: typeof ProductosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  FaqRoute: FaqRoute,
  GaleriaRoute: GaleriaRoute,
  NosotrosRoute: NosotrosRoute,
  ProductosRoute: ProductosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
